apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: default 
  name: hadoop-datanode1
spec:
  serviceName: "hadoop-datanode1"
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        component: hadoop-hdfs
        app: hadoop-datanode1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: hadoop-datanode1
          image: 10.254.0.50:5000/hadoop:latest 
          env:
            - name: HADOOP_NODE_TYPE 
              value: datanode
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HADOOP_MASTER_SERVICE 
              valueFrom:
                configMapKeyRef:
                  name: hadoop-conf
                  key: HDFS_MASTER_SERVICE
            - name: HADOOP_YRAN_MASTER  
              valueFrom:
                configMapKeyRef:
                  name: hadoop-conf
                  key: HADOOP_YARN_MASTER
          ports:
            - containerPort: 9000
            - containerPort: 50070
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
