apiVersion: v1
kind: Service
metadata:
  namespace: default 
  labels:
    component: hadoop-hdfs 
  name: hadoop-hdfs-master
spec:
  type: NodePort
  selector:
    app: hadoop-hdfs-master
  ports:
    - port: 9000 
      targetPort: 9000
      name: rpc
    - port: 50070
      targetPort: 50070 
      nodePort: 32007 
      name: http
